server:
  port: 8010
  servlet:
    context-path: /website
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf-8&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123997
